gowin_pack.py

Current configuration data checksum (l.1 in header, l2 in footer) is hardcoded.
The checksum, as mentionned in TN653 2.2.7, is an accumulation of consecutive 16bits.
This patch introduce this algorithm to update db.cmd_hdr and db.cmd_ftr.

gowin_pack: introduce the configuration data checksum computation

---

Makefile
readme.md

This will re-run the fuzzer and dat19_h4x when the relevant files change

add simple makefile for fuzzing

---

doc/commandstructure.md

This PR try to complete header line content description and to clarify bit/area unknown for futher analyze.

partial complement of the fs header

---

apycula/bslib.py
apycula/gowin_pack.py
doc/compression.md

bitstream compression is more or less the replacement of an serie `0x00` by a key.
this PR adds:
- CLI arg to enable compression
- header update with keys
- function to compress line
- a draft of algorithm's documentation
Tested with all devices supported by apicula

compress algorithm support

---

readme.md

I came trying to build for a RUNBER and was confused about what tec0117 was but put it in anyway, which obviously didn't work, ha! Figured it's be useful to be more explicit here.

Make it clearer what the example values are from

---

apycula/gowin_pack.py
apycula/tiled_fuzzer.py

All old modes are recognised correctly.

Fix unpacking IOB

---

doc/filestructure.md

Correct a minor error in the documentation.

---

readme.md

Show how to set the number of LEDs.
Pointed-out-by: newAM

Fix instructions for manual build of examples:

---

apycula/tiled_fuzzer.py

Allow the use of I2C pins iduring fuzzing.

---

doc/longval-tables.md

This is a very short description of what is found. IOB only.

Document the longval tables

---

apycula/gowin_unpack.py

Fix the .CST generation in the unpacker

---

.github/workflows/chipdb.yml
Makefile
apycula/bslib.py
apycula/chipdb.py
apycula/fuse_h4x.py
apycula/pindef.py
apycula/tiled_fuzzer.py
apycula/tm_h4x.py
examples/Makefile
examples/tangnano4k.cst

This currently generates bitstreams but the examples do not actually work because the IDCODE is wrong.

Add support for GW1NSR-4C

---

.gitignore
examples/tonegen/Makefile
examples/tonegen/README.md
examples/tonegen/cordic.v
examples/tonegen/sddac.v
examples/tonegen/tec0117.cst
examples/tonegen/top.v

In general it works, except for some version of the phase increment; see top.v

Tone generator using CORDIC and sigma-delta noise shaper.

---

apycula/gowin_pack.py

Yes, there's a such possibility here, too:)

Fix .CST creation in the gowin_pack

---

.github/workflows/chipdb.yml
Makefile
apycula/bslib.py
apycula/chipdb.py
apycula/codegen.py
apycula/tiled_fuzzer.py
examples/Makefile
examples/tangnano9k.cst

Its bitstream structure seems to be the same with GW1N-9, according to
openFPGALoader code.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

initial support for GW1N-9C

---

apycula/tiled_fuzzer.py

These cells, found in particular in GW1NZ-1, also have DFFs.

---

readme.md

See #85 re the invocation of Yosys. This also uses some variables instead of requiring changing device/board in multiple places.

Improvements to readme example

---

apycula/gowin_pack.py
apycula/tiled_fuzzer.py

It's actually empty, but it's the routing that counts.

Add the Global Set/Reset primitive

---

apycula/clock_fuzzer.py

Extrapolation of the clock wires to the outermost cells. This is
essentially an old fuzzer with a presumed location of the clock wires.
The probability of misplacement exists, but it is small.

Connect the outermost cells to the clock.

---

apycula/chipdb.py
apycula/gowin_unpack.py

Interpret "11110000000000000000" as an alternative ADD code. Works only in unpack --- you can't generate such a code.

Fix the ALU unpack

---

readme.md

readme.md: Clarify 9C footnote

---

doc/filestructure.md

Clarify the constants relating to long wires

---

examples/lutram/README.md
examples/lutram/build.sh
examples/lutram/lutram.v
examples/lutram/prbs.v
examples/lutram/top.v

Lutram example - tested on Gowin synthesis and Apicula/NextPnR.

Lutram example

---

apycula/gowin_unpack.py

Thanks to leeooox
https://github.com/YosysHQ/apicula/issues/115#issue-1283374512

Corrects a typo in the unpacker.

---

apycula/gowin_pack.py

packer: uniform type check

---

examples/Makefile
examples/globals/Makefile.inc

Add a directory with global network router tests

---

apycula/chipdb.py
apycula/tiled_fuzzer.py

Redo to autodetect the location of I/O banks

---

doc/filestructure.md

Document the logicinfo table

---

apycula/gowin_bba.py

The presence of these PIPs does not mean that they are functional, so until their mechanisms are clarified, we do not use them.

Do not send nextpnr wires of dubious purpose

---

apycula/clock_fuzzer.py

These rows are also nothing special, there are working GB and GT pips.

GW1N-9x: Add two rows as normal clock ones

---

.github/workflows/yowasp_examples.yml

Install yowasp from test pypy

---

apycula/chipdb.py
examples/Makefile
examples/pll.v
examples/pll/GW1NS-2C-dyn.vh

Also a curious design: some ports are moved so far away from the main cell that a search operation was required:)

stage2. Add PLL support for GW1NS-2 chips

---

apycula/gowin_unpack.py

BUGFIX: fix the "default" attribute unpacking

---

apycula/gowin_pack.py

Fix  https://github.com/YosysHQ/apicula/issues/175

BUGFIX: DFF and DFFN reset state

---

apycula/attrids.py
apycula/chipdb.py
apycula/gowin_pack.py
apycula/gowin_unpack.py

Revised PR, originally by uis246
* Take into account the fact that some inputs and outputs are in other cells from the primitive
* Clear energy conservation bits inherited from image template
* Enable OSC in the GW1NZ-1 chip by setting the impirical bits.
* Minor edits.

Added new oscillator types and improved its handling

---

gowin-pll.py

written in python,
only for the GW1N-9C
finds the best match

adding little helper tool like icepll

---

Makefile
apycula/gowin_bba.py
apycula/gowin_pack.py
apycula/gowin_unpack.py

Untested.
Hopefully should resolve our pypi compression problems.

use compressed pickle files

---

.github/workflows/chipdb.yml

update stable CI versions

---

.github/workflows/chipdb.yml
apycula/clock_fuzzer.py

Both architectures are created: legacy and Himbaechel

Modify CI to generate Himbaechel bases, build and test Himbaechel examples

---

readme.md

Doc. Mention SZFPGA (GW1NR-9) board as supported.

---

.github/workflows/chipdb.yml
Dockerfile
Makefile
apycula/bslib.py
setup.py

Fixed #217 and hopefully makes peoply trying to to bundle/install Apicual in weird ways a little happier for having to compile less C.

Switch crcmod to crc

---

.github/workflows/chipdb.yml

Let's see if this makes the CI green :heart_eyes:

bump yosys and nextpnr versions

---

apycula/chipdb.py
apycula/tiled_fuzzer.py

Allow using the architecture for calculating Fmax. Further work will consist of refining the wire classes and the values of time characteristics.

Add wire class info

---

apycula/chipdb.py

Perhaps in larger chips this is the range for another quadrant(s) of long wires.

Assign missing time delays

---

apycula/dat19.py

UserFlash description contained rubbish.

BUGFIX. Fix dat offset.

---

apycula/gowin_unpack.py

A typo in unpack spotted by @pecostm32.
Fixes #282

Fix mistype.

---

apycula/gowin_unpack.py

Fix another gowin_unpack mistype.

---

apycula/gowin_pll.py

Hello,
This PR fixes the range limit comments in the generated code by gowin_pll.py. It also removes extra identation on the generated code.

Fix pll codegen range limit comments

---

apycula/gowin_unpack.py
doc/architecture.md

Use SELx wires instead of direct LUT->FF conenction.

Unpack a DFFs with separated inputs from LUTs.

---

examples/blinky-clkdiv-dhcen.v
examples/blinky-clkdiv.v

When switching to the last HCLK, there was an oscillation - it would constantly reset to 0 and then back again.

Fix the CLKDIV examples.

---

apycula/chipdb.py
apycula/gowin_pack.py
apycula/gowin_unpack.py
examples/Makefile
examples/blinky-clkdiv-dhcen.v
examples/blinky-clkdiv.v
examples/miniszfpga.cst
examples/tangnano4k.cst

Adds support for CLKDIV2 and CLKDIV primitives for Tangnano1k, Tangnano4k, GW1N-1, GW1N-4 and GW1NR-9 boards.

Implement CLKDIV2 and CLKDIV for all boards.

---

apycula/tiled_fuzzer.py

In the current version of the IDE the files are the same, but it may happen that in the next version it will not be so:)

BUGFIX. Use correct IDE files.

---

apycula/gowin_pack.py

Do not ignore default attributes.
Fix #335

Use unspecified attributes for CLKDIV/CLKDIV2

---

setup.py

Remove a non-existent module from setup.

---

Dockerfile

Fixes a connection error when using the license server

work around license server issues
