gowin_pack.py
My python can't sum string bit vector.
=> gowin_pack.py: convert bits vector to int before sum

gowin_pack.py
for GENERIC_IOB type, attr is a dict where keys are "INPUT_USED" and "OUTPUT_USED" and values are number of input/output in string (binary representation).
Since values are string, tests:
```
if attr["INPUT_USED"]:
[...]
elif attr["OUTPUT_USED"]:
```
are based on empty/None instead of 0 or > 0.
So, first test is always true and output iob are generate as input too.
fix issue [#9](https://github.com/pepijndevos/apicula/issues/9)
PR [#8](https://github.com/pepijndevos/apicula/pull/8) must be applied too.
=> fix generic_iob direction detection

generic/simple.py
The current solution where exceptions are caught doesn't seem to work with newer versions of nextpnr. This issue is avoided by keeping track of added wires and not adding them at all instead.
=> Avoid adding duplicate wires

.github/workflows/chipdb.yml, Dockerfile
This will build the chipdb for each new commit to the master branch and upload it as a github artifact . Not sure if that is a bit redundant, but at least it runs automatically whenever stuff changes.
An example run of this can be seen in https://github.com/kbeckmann/apicula/actions/runs/193110067
The reason to why I changed `ADD` to `RUN curl..` is so that it gets cached. Docker will download the files every single time the container is built otherwise.
=> Add github workflow to build and upload chipdb

apycula/gowin_pack.py
- set axis argument to None/default in np.packbits
With this patch I do not see `CRC check : FAIL` anymore when flashing with openFPGALoad. Tested with:
```sh
cd examples/
rm -rf *.json
make
nextpnr-gowin --json blinky.json --write pnrblinky.json --device GW1NR-LV9QN881C6/I5 --cst tec0117.cst
gowin_pack -d GW1N-9 -o blinky.fs pnrblinky.json
openFPGALoader -b littleBee -r -f blinky.fs 
```
=> fix crc check fail when using python 3.8.5

examples/Makefile
- add steps to build all fs files by default
- add clean
- add prog to program blinky
This change enables to run blinky test on TEC0117 with:
```sh
make clean
make
make prog
```
=> Update build steps in Makefile

examples/Makefile, readme.md
Flash instruction and Makefile rules update:
- instead of using the ambiguous *littleBee* name a new entry *tec0117* has been added
- seeestudio runber is now officially supported
=> readme, examples/Makefile: fix openFPGALoader target board name

examples/Makefile, examples/blinky.v
By default the number of leds is hardcoded to 8. But depending to the targeted board this value is not always true and randoms pins are used for physical output not availables.
This PR add a verilog define to pass real number of leds:
- now it's no more possible to use a generic blinky.json to address all boards -> rule is renamed to append expliciitly board name and `synth` keyword
- the number of leds is provided trough Makefile variables
To clarify way to obtain number of leds:
```make
yosys -D LEDS_NR=$($(shell echo $(@) | cut -d\- -f 2)_leds) -p "synth_gowin -json $@" $^
```
is a two steps replacement:
1. `echo $(@) | cut -d\- -f 2` split rule name using '-' as separator and extract 2nd field (board name)
2. now `LEDS_NR=$($(shell echo $(@) | cut -d\- -f 2)_leds)` become …
=> examples: fix the number of leds according to the targeted board

Dockerfile, Makefile, apycula/bslib.py, apycula/chipdb.py, apycula/gowin_pack.py, apycula/tiled_fuzzer.py, examples/Makefile, examples/honeycomb.cst, readme.md, setup.py
This PR add support for GW1NS-2C FPGA:
The first commit avoid a crash like:
```bash
File "/xxx/apicula/apycula/gowin_pack.py", line 91, in place
bits = tiledata.bels['BANK'].modes['DEFAULT']
KeyError: 'BANK'
make: *** [Makefile:27 : blinky-honeycomb.fs] Erreur 1
```
Second commit add everything required to generate the pickle for this device and update readme (Dockerfile is partially updated -> needs to store xls somewhere)
And finally last commit add the honeycomb in examples
=> Support gw1ns 2c

apycula/gowin_unpack.py
=> Preparing for complex I/O modes and correcting minor errors.

apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py
Other than that:
- small comments in places to be corrected later
- a tiny speedup by changing the order of the loops
=> Use aliases of I/O standards in the packer

apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py
The generated files can be fed to the vendor p&r along with a netlist, which must be created by specifying the -vout and -json options simultaneously, e.g:
yosys -p "synth_gowin -vout shift-vout.v -json shift.json" shift.v 
nextpnr-gowin --json shift.json --write shift-pnr.json --device GW1N-LV1QN48C6/I5 --cst tangnannanno.cst
gowin_pack -d GW1N-1 -o ~/tmp/shift.fs --cst ~/tmp/shift.cst shift-pnr.json
You can then use shift-vout.v and ~/tmp/shift.cst as a new netlist/restriction pair to recompile.
At the moment both programs can contain bugs and gowin_pack gives better results compared to gowin_unpack:)
=> Create .cst (constraints) file from gowin_pack and gowin_unpack

apycula/chipdb.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py
The situation where an extra bit was captured meant that
only two identical registers could be placed in a single slide.
It is now possible to place registers of joint types, i.e:
DFFS and DFFR
DFFP and DFFC
DFFNS and DFFNR
DFFNP and DFFNC
as well as their CE versions.
=> Fix the fuzzing of the DFFs.

apycula/codegen.py, doc/longwires.md
Add ability to set constraint generation for fanout long wires.
Example:
cst.clocks["w_lw"] = "BUFS[5]=LOGIC"
=> Add long wire constraints.

apycula/chipdb.py, apycula/clock_fuzzer.py, apycula/gowin_bba.py, apycula/gowin_pack.py, apycula/pindef.py, apycula/tiled_fuzzer.py, apycula/tm_h4x.py, examples/Makefile, examples/tec0117.cst
=> Get info about packages/pins from the IDE files.

apycula/gowin_pack.py
Python does not copy structures on assignment :(
The error with bank attributes was harmless, with IO attributes not so much.
=> Fix base modification.

apycula/chipdb.py, apycula/gowin_bba.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py
The database is populated from tables for the following I/O attributes:
- PULL_MODE
- HYSTERESIS
- SLEW_RATE
- DRIVE
- OPEN_DRAIN
The SINGLE_RESISTOR attribute and the LVCMOS12 I/O standard are currently disabled.
Also the unpacking of the IOB is probably broken.
=> Get the IOB encoding from the vendor tables

apycula/chipdb.py
CUPCDN functionality seems to behave exactly the same with SUB, which
leads to unpacking failure when unpacking a bitstream that utilizes
SUB.
Mask the functionality in chipdb generation code now.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
=> chipdb: alu: mask CUPCDN functionality

apycula/chipdb.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py, doc/longval-tables.md
- store which mode is used for the case of inputs only;
- handle multiple banks in the same corner tile;
- add clock routes to the routing bits;
- warn if wrong IOSTD used for pin;
- use strings as the bank indices;
- the new IDE does not use a device configuration file, so do not write it;
- recoding update for GW1N-9;
- LVCMOS12 is back;
- document the 37 longval table.
=> Switch to read the banks encoding from .FSE

apycula/tiled_fuzzer.py
Not yet supported, so do not put untested fuses in the database.
They break the unpacking.
=> Disable T/IOBUF for ODDR

apycula/tiled_fuzzer.py
Bels A of IOB type 52 on the bottom side of the chip require VSS to be fed
to the two as yet unclear inputs.
=> Consider the feature of the GW1N-9 IOs

doc/longwires.md
Cell types 83 and 84 turned out to have muxes for the sources of those mysterious 40-47 wires.
=> Add new decoded cells associated with long wires.

apycula/gowin_unpack.py
Gowin tools do not understand dimensionless constant assignments and,
oddly enough, binary constants in the INIT parameter. So we specify the
dimensionality in the first case and use the hexadecimal representation
in the second.
=> gowin_unpack: Change the constant representation

apycula/clock_fuzzer.py
In chips with four quadrants this special line is served by the lower
spines, but in the case of two quadrants it belongs to the upper spines.
At the same time we forbid in it unknown (so far) PIPs to the system of
long wires.
=> Long wires: bugfix

apycula/gowin_pack.py
* Experiments with specialized routers can lead (in intermediate
branches they already do) to the use of fake cell types, which are not
encoded in any way, but only used to create the desired sequence of
PIPs. To avoid adding a lot of ignored types, it is proposed to ignore
types starting with DUMMY_.
* Removed swearing on the unknown type MUX2_, but the type itself is
left for the reason that although no action is required from the
packer, it is still a real cell type.
=> packer: generalization of ignored cell types

.github/workflows/chipdb.yml, .github/workflows/yowasp_examples.yml, Dockerfile, apycula/bslib.py, apycula/clock_fuzzer.py, apycula/fuse_h4x.py, apycula/gowin_pack.py, setup.py
To make apicula available in oss-cad-suite build I needed to make sure all python libraries are delivered as well, and there is problem building `pillow` in cross compile environment, also `pandas` was not used at all (and was causing some problems when doing cross compilation as well). 
Since `-png` option is anyway only for development, I just made sure it is available only if `pillow` is installed.
=> Make less dependencies required

apycula/chipdb.py, apycula/gowin_bba.py, apycula/pindef.py
Includes information on additional pin functions such as RPLL_C_IN, GCLKC_3, SCLK and others.
This allows a decision to be made about special network routing of such pins
=> Add information about the functions of the pins.o

apycula/clock_fuzzer.py
When there are only two quadrants, the bottom row appears to have no clock lines.
=> Do clock aliases on the bottom row

apycula/chipdb.py, apycula/wirenames.py, examples/Makefile, examples/pll-nanolcd/TOP.v, examples/pll-nanolcd/VGAMod.v
The nextpnr can now use the clock network to deliver PLL outputs if it sees fit.
On the apicula chip base side, all four outputs can be connected to the clock network, but the nextpnr currently has a limit of 3 networks, if I'm not mistaken. This is not being touched for the time being.
In the process of experimentation, the functions of the many internal wires of the large central clock MUX have been discovered and these are reflected in the names.
An example of using the PLL to form a picture on a 4.3" LCD screen is added.
! This commit uses the existing clock network processing logic and does not require any changes to the nextpnr, i.e. no new information about the big MUX device will be applied.
=> Add ability to use the clock net for PLL signals

apycula/clock_fuzzer.py
Corrects a mistake where non-existent wires were created for chips with 4 quadrants.
Fix https://github.com/YosysHQ/apicula/issues/143
=> Fix the creation of implicit clock wires

apycula/clock_fuzzer.py
These cells are served by the closest tap on the west side (according to GBx0 clock wire number) and clock fuzzer finds this perfectly, no GTx0 wires are used in the central column.
This did not cause errors, just no need to create wires leading nowhere and waste routing time.
=> Don't create GTx aliases along the central column

apycula/chipdb.py, apycula/clock_fuzzer.py, apycula/gowin_pack.py, apycula/wirenames.py
Storing and using part of the "alonenode" table to set fuses designed to disable "lone" nodes, i.e. nodes that are not used as sources. It is used to switch long wires in buses.
In addition, the representation of long wires is greatly simplified by creating only the necessary aliases and transferring the main work to the nextpnr.
It should be noted that only table #6 of the "alonenode" family is involved, since the function of table #69 remains unclear.
=> Add the alonenode mechanism

apycula/chipdb.py, apycula/clock_fuzzer.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, examples/Makefile, examples/pll-nanolcd/TOP.v, examples/pll.v, examples/pll/GW1N-1-dyn.vh, examples/pll/GW1N-9C-dyn.vh, examples/pll/pllvr.v, examples/pll/rpll.v, examples/pll2.v, examples/tangnano9k.cst
* Both PLLs with all attributes are supported;
* Static and dynamic setting of generated frequencies;
* New approach to handling multi-cell primitives: now all ports scattered over cells are represented by aliases to the main cell, auxiliary cells are simply ignored in nextpnr;
* A mechanism for describing ports located in auxiliary cells was discovered.
* examples/pll2.v demonstrates the use of two PLLs simultaneously on a Tangnano9k board
* also added an example with signal generation for VGA LCD using PLL
=> stage 2: Add support for GW1NR-9C PLL

apycula/chipdb.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py
DFFs are assembled from parts depending on the type, also when unpacking the type is reconstructed from the used functional parts, which means "clock line inversion", "asynchrony", "triggering by SET or RESET", etc.
=> Replace DFF fuzzer with table data

apycula/tiled_fuzzer.py
The mechanism of enabling IOBA as IO in the GW1NR-9(c) chips is still unclear, but the old names are quite vague and there is a danger of finally forgetting their purpose.
=> BUGFIX: assign slightly more meaningful names

.github/workflows/chipdb.yml, Makefile, apycula/bslib.py, apycula/chipdb.py, apycula/codegen.py, apycula/tiled_fuzzer.py, examples/Makefile, examples/primer20k.cst
Only the chip GW2A-LV18PG256C8/I7, which is installed in Primer20k.
Support in the volume of workable blinky, no more.
=> Add support for the GW2A series 

apycula/gowin_bba.py, apycula/gowin_pack.py, apycula/gowin_unpack.py
to restore python 3.8 support in https://github.com/YosysHQ/oss-cad-suite-build/releases 
untested; hope to download apycula.egg artifact and test using that
=> python 3.8 support for importlib files api

apycula/gowin_pack.py
The coding of the OPEN_DRAIN attribute turned out to be not so unambiguous. It looks like there is ON / OFF and one more default state.
As a temporary measure, setting OPEN_DRAIN=OFF is ignored, but you use OPENDRAIN=ON at your own peril and risk.
=> Fix OPEN_DRAIN IO attribute

examples/himbaechel/blinky-osc.v, examples/himbaechel/blinky-pll-vr.v, examples/himbaechel/blinky-pll.v, examples/himbaechel/blinky.v
Examples consisting of ALUs and DFFs can pack well so there is no need for a LUT. This after causes problems when checking unpacking. Add a simple LUT.
=> Fix simple examples

apycula/ini_h4x.py, doc/filestructure.md, readme.md
This Pull Request adds a module `apycula/ini_h4x.py` for parsing vendor-provided .ini files and edits the documentation to reflect the availability of a `.ini` parser. 
The `.ini` file is a somewhat compressed table of IO Types and associated configuration options. The table has four sections -- `input`, `output`, `bidirectional`, and the optional `i3c_bank`.
`ini_h4x.py` provides an `IniParser` class for parsing `.ini` files. After the `parse()` method is called, the various sections of a parsed `.ini` file(`input, output, bidirectional, i3c_bank`) may be accessed via dot notation, or modified and written to a csv.
```
iniParser = IniParser("GW1N-4")
iniParser.parse()
input_dict = iniParser.input
```
`ini_h4x.py` also exposes a simple command line tool to parse `.ini` files into `csv`; …
=> A Parser For Vendor Provided .ini Files

apycula/gowin_pack.py
When switching to Python 3.8, the parsed device was lost.
https://github.com/YosysHQ/apicula/issues/213
=> BUGFIX: Use parsed device.

.github/workflows/chipdb.yml, apycula/dat19.py
My changes to the DAT file parser do not run on Python3.8 and the validation tests passed, as they run on Python3.9.
If bumping the requirement to 3.9 is not reasonable, this PR adds a sanity check by executing `gowin_pack` on 3.8.
I added the check to the `pypi` job to prevent the publish step from being runnable, but I could also move this into a new job that runs on 3.8
=> Fix #219: Python3.8 compatiblity

Makefile, apycula/chipdb.py
The GW1NR-9C has interesting clock pins on the bottom side - they do not connect directly to the central MUX, but pass through an additional MUX in the corner cell. Let's take this into account.
=> Properly handle external 9C clock pins

apycula/gowin_pack.py
There's actually very little going on on the apicula side, but a future nextpnr fix will split each of IOLOGICA and IOLOGICB into two directions: IOLOGIC in and IOLOGIC out. This allows us to combine two IOLOGICs at once to work with IOBUF, which addresses issue https://github.com/YosysHQ/nextpnr/issues/1275
The nature of the fixes in this PR is such that it will work with the old version of nextpnr and everything that successfully passes through netxpnr will work.
=> Add support for four IOLOGICs in one cell

doc/sdram.md
This pull request extends the existing SDRAM documentation to include the pinout of the embedded SDRAM on the GW2AR-18 devices, among other minor changes. The information provided is almost certainly correct and has been verified by analysing the vendor-generated bitstream from a design that uses the embedded SDRAM controller IP.
=> Extend SDRAM Documentation to Cover GW2AR-18 Devices

examples/himbaechel/tangnano4k.cst
The point is that the external crystal on this board is soldered to a pin, which is a PLL input, not a clock pin. Therefore, common routing is used.
By specifying that this is a buffered network, we are forcing the router to use global clock wires.
=> Examples. Describe the Tangnano4k clock pin.

apycula/bitmatrix.py, apycula/bslib.py, apycula/chipdb.py, apycula/clock_fuzzer.py, apycula/fuse_h4x.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py, setup.py
Dumb replacement of functions. The functions work only to the extent required, no more.
Creating chip databases (this includes fuzzing etc), packing and unpacking work.
Special moments:
* you will still need numpy to create the PNG, but the import only happens when that function is called.
* compression packing needs to be tested.
* perhaps somewhere in places that I rarely use there are numpy calls.
Addresses https://github.com/YosysHQ/apicula/issues/224
=> Replace numpy arrays with lists.

apycula/tiled_fuzzer.py, examples/himbaechel/Makefile.himbaechel, examples/himbaechel/clockworks.v, examples/himbaechel/emitter_uart.v, examples/himbaechel/femto-riscv-15.v, examples/himbaechel/femto-riscv-16.v, examples/himbaechel/femto-riscv-18.v, examples/himbaechel/riscv_assembly.v, examples/himbaechel/tangnano20k.cst, examples/himbaechel/tangnano4k.cst, examples/himbaechel/tangnano9k.cst
Examples of implementation of lessons 15, 16 and 18 from the Bruno Levy course are added
(https://github.com/BrunoLevy/learn-fpga/blob/master/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/README.md).
These are parts devoted to the use of inferred BRAM for reading (15), for writing (16) and a complex example with the output of the Malderbrot set via UART (18).  Lessons are implemented for Tangnano4k, Tangnano9k and Tangnano20k boards.
The main function of these three examples is to serve as a canary in the mine, to detect regressions when making changes - like attosoc, but with the possibility of gradually simplifying the design - in particularly difficult cases, you can move along the original lessons from the 15th down to the 1st.
Since no new primitives are used there, there is no point in …
=> Add examples with tiny RISCV

apycula/fuse_h4x.py
This pull request adds two functions (`parse_tile_exact` and `exact_table_cover`) to `fuse_h4x.py`. The `parse_tile_exact` reports an exact cover over the rows in a table, computed using the `exact_table_cover`  function that are 'active' in a bitstream.
These functions come from the realization that the problem of determining what rows in a table were actually used can be conceptualized as an exact cover problem, assuming that no two active rows ever share fuses. So far, this assumption seems to hold up.  
These functions are quite effective at cutting out 'noise'. Consider the following comparison between the output of parse_tile and parse_tile_exact for the same tile. 
`parse_tile`
```
[2, 10, (0, 35)]
[3, 10, (0, 35), (0, 34)]
[8, 10, (0, 34)]
[81, 3, (0, 48), (0, 45)]
[82, 3, (0, …
```
=> Add Functions for Concise Tile Parsing

.github/workflows/chipdb.yml
It seems like Yosys renamed their main branch, breaking our CI
https://github.com/YosysHQ/yosys/pull/4297
=> update yosys CI branches

apycula/chipdb.py, apycula/pindef.py, apycula/tiled_fuzzer.py, examples/himbaechel/Makefile.himbaechel, examples/himbaechel/dual-pll-vr.v
Whenever possible, we arrange the PLL so as to use a direct connection of pins to the inputs of the primitive. The main work happens in nextpnr-himbaechel, here we only prepare data about which pin corresponds to which PLL.
Also added an example for Tangnano4k where two PLLs compete for one input pin. Only one of them can win, but both must function.
=> Add PLL pads.

apycula/gowin_unpack.py
Some chips may only have B pins in some IO blocks. Don’t break down in such a situation.
=> Fix IO unpack

apycula/chipdb.py, examples/himbaechel/Makefile.himbaechel, examples/himbaechel/femto-riscv-15.v, examples/himbaechel/femto-riscv-18.v, examples/himbaechel/miniszfpga.cst
Chips that have features in the implementation of BSRAM are marked with special flags, to which nextpnr reacts by adding corrective primitives such as LUTs and DFFs and changing routing if necessary.
Currently this is a fix for WRE-CE signals in Single Port BSRAM and a fix for READ_MODE=1'b1 (pipeline).
A .CST file is also added for the reduced SZFPGA board - it uses a GW1N-9 chip in a 48-pin package versus a “full-fledged” SZFPGA with a GW1NR-9 chip in a 144-pin package.
=> BSRAM. Corrective action.

apycula/gowin_pack.py
Allow only non-zero BSRAM initialization lines to be specified - such a netlist has also been found in the wild :)
=> Relax BSRAM initialization data requirements

apycula/gowin_pack.py
We bring it into line with what is observed in the Gowin images - in the ROM, port A has a signal CE = VCC and inversion is turned on on this pin. We will provide VCC in nextpnr, and enable the inversion here.
=> Fix pROM(X9).

apycula/chipdb.py, apycula/gowin_pack.py, examples/himbaechel/bandgap.v
As the board on the GW1N-1 chip becomes a rarity, its replacement is the Tangnano1k board with the GW1NZ-1 chip. This chip has a unique mechanism for turning off power to important things such as OSC, PLL, etc.
Here we introduce a primitive that allows energy saving to be controlled dynamically.
Nextpnr will add this primitive automatically if we do not use it explicitly - this is done to explicitly connect the control input since its default connection is neither VCC nor GND.
BANDGAP only has an input, but does not have a fuse - it is on all the time. Of course, a reasonable question arises - what are these magic numbers in line 2258-2259 of gowin_pack.py?
I really don’t want to consider these BANDGAP fuses precisely because this primitive is not configurable - and these bits are fuses …
=> Implement power saving primitive BANDGAP

apycula/bitmatrix.py
The old version did not work when the number of bits in the line was not a multiple of 8. This manifested itself in an incorrect CRC calculation for boards with the GW1N-9C chip.
=> Fix bits to bytes conversion.

apycula/chipdb.py
We add the ability to use a direct connection of the clock pins on the chip side with the HCLKs input on the corresponding side for the GW1N-9C.
For other chips this standard feature is automatically supported, but 9C is unique - here the wires are renamed.
This is not supported on the bottom side of the chip yet and probably won't be in the near future - but this is not a problem since the external clock generator on the Tangnano9k board is connected to the right side of the chip.
=> HCLK. Primary clock pins

apycula/chipdb.py
Bring to a unified way of finding out the functions of cells.
=> Remove the magic numbers

examples/himbaechel/tangnano9k.cst
Pins 17 and 18 on the Tangnano9k board can be used as UART over USB to communicate with a big computer. It allows to use the same cable used for programming, without additional devices.
=> Use builtin USB-serial

Makefile, apycula/chipdb.py, apycula/codegen.py, apycula/find_sdram_pins.py, apycula/tiled_fuzzer.py, examples/Makefile
While we have documented the sdram pins of some devices we lack the ability to automatically place them like the vendor tools do. For better compatibility and user friendliness this PR adds the ability to fuzz these magic pin locations.
=> add magic sdram pin constraints

examples/himbaechel/Makefile.himbaechel, examples/himbaechel/iddr.v, examples/himbaechel/iddrc.v
I found out the bandgap and mul18 examples were not being built.
It seems like on GW1N-4 devices the example errors, not sure why.
=> add missing examples to makefile

apycula/gowin_pack.py, apycula/gowin_pll.py
Hello,
This PR sets the PLL limits of GW2A-18 C8/I7 according to [DS226E](https://cdn.gowinsemi.com.cn/DS226E.pdf).
=> Fix PLL limits for GW2A-18 C8/I7

readme.md
The footnote mentions "`C`-devices" but I can't quite figure out what that means
Edit: Oh, I found `examples/himbaechel`. I'll repoint the footnote to that since it seems to be the big new thing
~~I also now realized that there is no example for this board so I attempted to create one. I'm a bit surprised to see `nextpnr-gowin` in the examples since I thought that was deprecated and replaced by himabechel. Since I don't have -gowin installed, I tried to at least create the example using -himbaechel for porting later.
However, with this `cst` file
```
IO_LOC "clk" 4;
IO_LOC "led[0]" 15;
IO_LOC "led[1]" 16;
IO_LOC "led[2]" 17;
IO_LOC "led[3]" 18;
IO_LOC "led[4]" 19;
IO_LOC "led[5]" 20;
```
I get
```
nextpnr-himbaechel --json blinky-tangnano20k-synth.json --write blinky-tangnano20k.json …
```
=> WIP: Add family footnote to 20k-boards

examples/himbaechel/Makefile.himbaechel
Essentially specifying the gw2a family to compile examples for Tangnano20k and TangPrimer20k
=> Adapt the examples to the latest Yosys

apycula/chipdb.py, apycula/gowin_pack.py, examples/himbaechel/iddr.v, examples/himbaechel/ides4.v
This sensor will in the future allow dynamic control of the delay line at the IBUF input. At the moment, the changes to the examples only verify that the primitive compiles successfully.
This primitive is similar to MUXes in the sense that it has no fuses, it is always on and it is up to the user to use the signals on its outputs or not.
=> Add IEM (Input Edge Monitor)

apycula/chipdb.py
This should suffice to get `CUPCDN` working. Closes #300.
=> Restore CUPCDN with a different bit pattern

examples/himbaechel/ioregs.v
There are three registers in IO blocks: IREG, OREG, and TREG. Not in all of them, but only where there is IOLOGIC because these registers are part of it.
Hence the first limitation: if FF is placed in an IO block, the rest of the IOLOGIC cannot be used.
The second limitation is related to the fact that all three registers have common wires CLK, ClockEnable and LocalSetReset and this dictates the types of flipflop's - let's say DFF (in Gowin's implementation) requires a constant connection CE to VCC, so you can not use in the same IO block DFFE, which CE is a signal.
=> Implement FF in IO blocks.

apycula/gowin_pack.py
This causes a warning to be printed on stderr when running `apicula.gowin_pack.main()` directly (but not via the CLI).
=> gowin_pack: fix invalid escape sequence

apycula/chipdb.py, apycula/gowin_pack.py, examples/blinky-pll.v
Adds the ability to use high-speed clock lines (together with CLKDIV2 type frequency dividers operating on them) as signals for the CLKIN and CLKFB inputs of the rPLL and PLLVR primitives (these cover the full range of supported Gowin chips).
=> Add HCLK wires to PLL.

apycula/chipdb.py, apycula/gowin_pack.py, apycula/gowin_unpack.py
Briefly, these wires can be described as connecting directly to the sinks in a rectangle 4 columns wide and at least 10 rows high. The source can be either at the upper end or at the lower end, which is connected by a system of ‘isolation’ of unused ends.
These small nets are useful when the global ones are exhausted or they are not suitable for a given type of sink and/or source - these wires are omnivorous.
=> Add segmented clock wires.

apycula/attrids.py, apycula/chipdb.py, apycula/gowin_pack.py, apycula/gowin_unpack.py
DLLDLY is the clock delay primitive that adjust the input clock according to the DLLSTEP signal and outputs the delayed clock.
These primitives are associated with clock pins and are "tapped" between the output of this IBUF and the clock networks, leaving the possibility to connect to the original unshifted signal as well, although the latter is not very practical because it is no longer possible to use fast wires.
=> Implement the DLLDLY primitive.

apycula/chipdb.py
Nextpnr tracks spines 6 and 7 and will not allow their use without DCS, but segments associated with 6 and 7 can't necessarily rooute through the spines, so allow their use. This will free up general purpose wires.
=> Eanble segments associated with spines 6 and 7.

apycula/bitmatrix.py, apycula/bslib.py, apycula/gowin_pack.py, doc/compression.md, examples/Makefile
Bitstream compression (gowin_pack -c) seems broken after numpy is removed. This fixes it. 
The histogram version was broken because bs is actually a 2D array. Passing [y for x in bs for x in y] as a parameter would also work, but I just used built-in itertools for a (marginally) slight performance gain.
=> Fixed bitstream compression, tested on tangnano 9k hardware

apycula/chipdb.py
They have been removed in Python 3.14.
https://github.com/python/cpython/commit/2f4db5a04d6fa7ba5c1c6b82b482dd7ca48f3382
=> Remove ByteString usages

apycula/attrids.py, apycula/bslib.py, apycula/chipdb.py, apycula/gowin_pack.py, apycula/tiled_fuzzer.py
We remove the original template from the chip base, which resulted from compiling an empty module.
Now there is no need in it - we set all the necessary bits ourselves.
At this point, the compilation call still remains - for header and footer.
=> Remove bitstream templates.

apycula/bitmatrix.py, apycula/bslib.py
Working with a fixed number (256) of baskets speeds up packing.
before
``` shell
% time gmake dsp-alu54d-miniszfpga.fs
gowin_pack -c -d GW1N-9 -o dsp-alu54d-miniszfpga.fs dsp-alu54d-miniszfpga.json
Warning. No unused bytes, will be uncompressed.
gmake dsp-alu54d-miniszfpga.fs  25,33s user 0,14s system 97% cpu 26,170 total
```
after
``` shell
% time gmake dsp-alu54d-miniszfpga.fs
gowin_pack -c -d GW1N-9 -o dsp-alu54d-miniszfpga.fs dsp-alu54d-miniszfpga.json
Warning. No unused bytes, will be uncompressed.
gmake dsp-alu54d-miniszfpga.fs  6,05s user 0,15s system 99% cpu 6,257 total
```
=> Use a special case of the histogram.

apycula/attrids.py, apycula/gowin_pack.py, examples/gw5a/Makefile
The TangPrimer25k board is designed so that the external quartz resonator is soldered to the E2 input, which is the communication line to the CPU/SSPI.
Without further ado, we add a command line flag to use it as a GPIO to receive the clock signal.
=> GW5A. Add CPU/SSPI contact mode switching.

apycula/chipdb.py, apycula/gowin_pack.py, apycula/gowin_unpack.py, apycula/tiled_fuzzer.py, apycula/wirenames.py
The 5A family brings significant changes to the wiring, especially in terms of clocks. For example, previously there were two pins on each side of the chip for connecting external clock sources, but now there are four on each side. Previously, the PLL had one CLKOUT and a couple of derivative outputs, but now there are 7 independent CLKOUTs for each PLL. And there is an unknown number of new HCLK wires.
These new wires do not fit well into the existing tables, so we will try to split them up.
The select_wires(device) call will select which set of tables to continue working with.
At the moment, they are the same.
=> Separate wire descriptions

apycula/chipdb.py, doc/alu.md, examples/gw5a/Makefile
We are enabling ALU generation in the GW5A series chip database, supplementing the ALU documentation and correcting the examples to use ALU.
=> GW5A. Enable ALU.

apycula/chipdb.py, apycula/find_sdram_pins.py, apycula/gowin_pack.py, apycula/gowin_unpack.py
We accelerate the creation of a bit image because there are many searches for attribute-value pairs, and in the previous version this was done by brute force.
=> Turn the logicinfo lists to the dictionaries.

doc/commandstructure.md
In the GW5A series, some fairly large functional blocks are located outside the main grid—that is, the grid has wires for pins, almost always scattered across several cells, but there are no functional fuses—these fuses are installed in special blocks (slots) that are not geometrically related to the main grid.
Fuses are described in tables with types >1024, although there are naturally no tiles of this type, since there is no place for them in the main grid.
Each slot has a unique number that determines which primitive is located in it.
In fact, it is quite easy to determine the purpose of the slots—the output file contains blocks describing the slots used. So, if the lower left PLL is used (Gowin IDE allows you to specify the desired location of primitives), then the output file will …
=> Document the slots.

apycula/chipdb.py
Due to an oversight, the bottom side of the chip did not receive IOB adjustments, which caused problems with the use of the TangPrimer25k onboard USB-UART board.
Fixed.
=> GW5A. BUGFIX. Bottom IOs.

apycula/tm_h4x.py
We enable the use of the same time data under different names.
Like ES = A0 = C1/I0
=> Add a speed grade aliases.

apycula/gowin_pack.py
GW5A series.
The O-part was not activated in IOBUF.
=> IO. Fix IOBUF.
